### ISSUE TITLE
Reflect real state of machine in its status

### ISSUE THREAD

**Issue by ingvagabund** [openshift/cluster-api-provider-aws#4]
Update the status loop to actually update the machine status based on the real instance state (e.g. if it's either running or still in pending state, public IPs assigned if set, etc.)

**Comment by dgoodwin** [comment]
I think this was actually implemented but broken because the status was first written with apiVersion:

```
    providerStatus:         
      apiVersion: cluster.k8s.io/v1alpha1
      conditions: null
      instanceId: i-0675b4b3aa9dabdfc
      instanceState: pending                    
      kind: AWSMachineProviderStatus      
```

And when we went to decode it to update, it would fail to decode. (that error was silently being swallowed btw, we need to make sure that errors from the actuator are getting logged somewhere somehow)

Working on a fix.
